apiVersion: v1
kind: Service
metadata:
  name: my-spring-app-service
spec:
  type: LoadBalancer            # LoadBalancer 타입으로 설정
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 8080                # 외부에서 접근할 포트
      targetPort: 8080          # 파드의 컨테이너 내부 포트