apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-deployment
spec:
  replicas: 1  # 시작할 파드 수
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
      - name: my-spring-container
        image: my-spring-image:latest  # 빌드한 이미지 이름
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"