apiVersion: v1
kind: Service
metadata:
  name: my-spring-service
spec:
  type: LoadBalancer  # LoadBalancer로 타입 변경
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 8080       # 외부에서 접근할 포트
      targetPort: 8080 # 파드에서 애플리케이션이 사용하는 포트